- - existing
- - react-devtools
- - react-devtools-shell
- - react-devtools-core
- - react-devtools-inline
- - react-devtools-extensions
- [ react-art, react-devtools-shared, react-interactions, react-refresh ]
- - react-test-renderer
- [ react-dom, react-native-renderer, react-noop-renderer ]
- [ legacy-events, react-reconciler ]
- [ create-subscription, jest-mock-scheduler, jest-react, react-cache, react-is, react-stream, use-subscription ]
- [ babel-plugin-react-jsx, eslint-plugin-react-hooks, react, react-debug-tools, scheduler, shared ]